### ISSUE TITLE
Add Django

### ISSUE THREAD

**Issue by Adilmrqureshi** [inngest/inngest-py#21]

**Comment by goodoldneon** [comment]
I added Django support in newly-published version `0.2.1`. Let me know what you think!

Here's an example of a barebones Django app using it the new integration:
https://github.com/inngest/inngest-py/blob/main/examples/django/app.py

**Comment by goodoldneon** [comment]
Closing this since we have official Django support now. Feel free to open a new issue if you have any problems with our Django integration
