### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by slep0v** [inngest/inngest-py#61]
Hello, do you have plans to add support for python 3.9?

This will allow inngest-py apps to be hosted on vercel, as they support only 3.9 python as of now.

**Comment by goodoldneon** [comment]
We'll look into it! It looks like the only two >=3.10 things were using are [PEP 604](https://peps.python.org/pep-0604) and [PEP 647](https://peps.python.org/pep-0647). Both of those have backports for older Python versions, so supporting 3.9 should be possible with some changes on our end

**Comment by goodoldneon** [comment]
Released Python 3.9 support in version `0.3.6`!
