### ISSUE TITLE
Add DigitalOcean Functions

### ISSUE THREAD

**Issue by suledev** [inngest/inngest-py#76]
It would be great to be able to use the SDK with DigitalOcean functions.

**Comment by goodoldneon** [comment]
We'll work on this soon!

**Comment by goodoldneon** [comment]
We added DigitalOcean Function support in version `0.3.13`. This release also includes a development-only `DigitalOceanSimulator` class that allows you to test your code locally against the Inngest Dev Server.

We'll update our docs to include DigitalOcean soon
